### ISSUE TITLE
In case of incorrect translation : Logging in ASP.NET Core

### ISSUE THREAD

**Issue by dotkebi** [aspnet/AspNetCore.Docs.ko-kr#126]
`Logging in ASP.NET Core`을  `ASP.NET Core에 로그인`이라고 번역했습니다.
이는 `Logging`을 `Login`으로 번역한 것으로 완전히 다른 뜻입니다.

참고해서 수정해 주시기 바랍니다.

It translated `Logging in ASP.NET Core` as` Login to ASP.NET Core`.
This is a completely different interpretation of translating `Logging` into` Login`.

Please correct it.

**Comment by CeciAc** [comment]
Hello, @dotkebi 

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged.
Please review issue https://github.com/dotkebi/AspNetCore.Docs.ko-kr/commit/36621766d6bf5a2fd2c649975b457387340f2824 . For this reason we are closing this issue since it is duplicated.

Kind regards,
Microsoft DOCS International Team
